public  class Calculator {
    public static void welcomeMessage() {
        system.debug('welcome to apex calC');
    }
     public static void printNewMessage(string msg){
     system.debug(msg);
     }

     public  static integer add(integer a, integer b){
         integer sum = a + b;
         return sum;
     }
     //add method with 3 params
    public static integer add(integer a, integer b, integer c){
        return a+b+c;
    }
    public static integer add(List<integer> intList){
        integer sum = 0;
        

        return returnInt;
    }

    
}
