DmlDemo.dmlInsertDemo_stndObj();
// list<account> listAcc = new list<account>();
// for (Integer i = 0; i < 4; i++){
//     account acc2 = new account();
//     acc2.Name = 'SoftInnovas 10-May v'+i;
//     acc2.AccountNumber = 'asci-1'+i;
//     acc2.Active__c = 'Yes';
//     listAcc.add(acc2);
// }
// system.debug('size of list ' + listAcc.size());

// if(!listAcc.isEmpty()){
//     insert listAcc;
// }