system.debug('Derse hosgeldiniz..');
string str = 'Salesforce ogreniyorum..';
system.debug(str);
 
 integer Nmbr = 10;
 system.debug(Nmbr);
 Nmbr = 15;
 system.debug(Nmbr);
  
  integer a = 45;
  integer b = 5;
  integer c = a + b;
  integer d = a/b;
  system.debug(' a sayisi ='+ a +'b sayisi = ' + b);
  system.debug( ' c sayisi = '+ c + 'd sayisi = 'd);
   system.debug('hello');
   system.debug('Hello Zuleyha');