TurkisLesson2 tl = new TurkisLesson2();
//system.debug('obje ->'+ tl)
tl.variableDefine();
tl.text = 'Salesforce ogrendim..';
system.debug('tl objesi = ' + tl);
 TurkisLesson2 t2 = new TurkisLesson2();
 t2.welcome('zuleyha ');
 t2.welcome('Fatih ');
 t2.welcome('Salih ');
 t2.welcome('Melih ');
  
  TurkisLesson2 t3 = new TurkisLesson2();
  t3.welcome('esma');
  
  TurkisLesson2 t4 = new TurkisLesson2();
intiger lng = t4.stringMetot('Hello World');
  system.debug(lng)